### ISSUE TITLE
Gestion de categorias

### ISSUE THREAD

**Issue by e-caceres** [MyTravelsApp/my-travels-app#1]
Realizar el mantenimiento de las categorias. Ponerlo como una lista simple con un campo solo que sea descripcion. Mirar si se puede seleccionar un color para identificarla.

Subtareas:
- [x]  Añadir funcionalidad al botón cancelar
- [x]  Controlar si la categoria esta asociada a un travel places.
- [x] Permitir la edición de una categoria.

**Comment by e-caceres** [comment]
Esto podria ayudar:
http://stackoverflow.com/questions/31844373/saving-edittext-content-in-recyclerview
http://stackoverflow.com/questions/26076965/android-recyclerview-addition-removal-of-items

**Comment by fjtorres** [comment]
En la siguiente URL se muestra como tratar un elemento al final de un recyclerview, de este modo podremos añadir un botón al final.

http://stackoverflow.com/questions/29106484/how-to-add-a-button-at-the-end-of-recyclerview

**Comment by e-caceres** [comment]
Cuando se va seleccionando categorias y la nue

**Comment by e-caceres** [comment]
Al borrar una categoria comprobar si tiene travelplaces asociados. Si tiene mostrar mensaje de confirmación previo al borrado.

**Comment by e-caceres** [comment]
Antes de cerrar este issue queda volver a añadir a la lista la categoria seleccionada para borrar cuando decimos que no queremos eliminarla.
