### ISSUE TITLE
Funcionalidad deshacer

### ISSUE THREAD

**Issue by e-caceres** [MyTravelsApp/my-travels-app#11]
Es necesario repasar la funcionalidad de deshacer eliminado ya que el borrado se hace efectivo al ocultarse la barra deshacer. Deberia de hacerse efectivo y guardarse en memoria por si se deshace la acción.

**Comment by fjtorres** [comment]
Se podría consultar en el grupo de facebook del cadizdevelopers, mucha gente competente a nivel nacional sigue ese grupo (Gente de karumi, job&talent, etc.).

**Comment by e-caceres** [comment]
Segun hablamos esto esta bien asi ¿Verdad? ¿Se puede cerrar issue?

https://github.com/karumi/rosie

**Comment by fjtorres** [comment]
Controlar el borrado cuando se pasa a segundo plano la actividad o fragmento, ya que ahora mismo no borra el elemento y puede ser extraño. Por ejemplo si borramos y luego hacemos click en un elemento del listado no se llega a borrar.
