### ISSUE TITLE
Deshacer borrado de elementos

### ISSUE THREAD

**Issue by e-caceres** [MyTravelsApp/my-travels-app#2]
Se debe de poder deshacer la acción de eliminar un elemento. La idea seria de mostrar una notificación en la barra inferior parecida a que muestra gmail al eliminar un correo.

Se debe añadir a la opción de eliminar en los siguientes módulos:
- [x]  Viajes
- [x]  Puntos de interés
- [x]  Categorías

**Comment by fjtorres** [comment]
La idea seria utilizar el snackbar indicando un callback donde se controle el método *onDismissed*, si el evento es distinto de *DISMISS_EVENT_ACTION* el borrado es permanente.

**Ejemplo de como usar el snackbar**
- http://www.androidhive.info/2015/09/android-material-design-snackbar-example/ 

**Información util para hacer la funcionalidad que permita deshacer el borrado**
- http://stackoverflow.com/questions/30926380/how-can-i-be-notified-when-a-snackbar-has-dismissed-itself
- http://developer.android.com/reference/android/support/design/widget/Snackbar.Callback.html

**Comment by fjtorres** [comment]
Añadido comportamiento a la funcionalidad de eliminar viaje.

**Comment by e-caceres** [comment]
Hay que usar la opcion indeterminada *Snackbar.LENGTH_INDEFINITE*. La opcion "long" es demasiado corta.
