### ISSUE TITLE
Crear la planificación del viaje

### ISSUE THREAD

**Issue by fjtorres** [MyTravelsApp/my-travels-app#4]
Crear las ventanas que permitan realizar la planificación del viaje, se debe permitir **asignar** diferentes **puntos de interés a los días del viaje** y en la medida de lo posible **organizar** los puntos de interés **en un orden definido por el usuario**.
- [x] Listado de días.
- [x] Selección de los puntos.
- [x] Cambiar titulo según el fragmento que este visible, para diferenciar selección de los seleccionados.
- [x] Controlar correctamente el botón atrás.
- [x] Controlar el borrado de puntos, debería eliminar el punto de los días donde estén asociados.
- [x] Ordenación de puntos dentro del día.

**Comment by fjtorres** [comment]
Enlaces para el tema de la selección de elementos.

https://github.com/writtmeyer/recyclerviewdemo/blob/master/app/src/main/java/com/grokkingandroid/samplesapp/samples/recyclerviewdemo/RecyclerViewDemoActivity.java

http://www.grokkingandroid.com/statelistdrawables-for-recyclerview-selection/

**Comment by fjtorres** [comment]
http://enoent.fr/blog/2015/01/18/recyclerview-basics/

**Comment by fjtorres** [comment]
Modificar el titulo a la hora de seleccionar los puntos, ahora mismo no cambia y parece la misma ventana.

**Comment by fjtorres** [comment]
Revisar si al borrar un punto de interés se elimina de los días asociados, recordar que se almacena como una cadena json en la entidad por lo que no existe una relación de integridad referencial.

**Comment by fjtorres** [comment]
El borrado de puntos de interés elimina correctamente los elementos asociados en la planificación.

**Comment by e-caceres** [comment]
Se ha corregido el boton atras.
